### ISSUE TITLE
OpenStudioApplication 1.2.0 - Release Checklist

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#353]
- [x] Release Notes
- [x] Update OSM libraries to the right SDK version
- [x] Test Windows Installer
    - [x] Julien: clean Win10 VM (rc3)
- [x] Test Mac Installer
- [x] Test Ubuntu 18.04 Installer
    - [x] Julien (Note: on a developper machine) (rc3)
- [x] Test Ubuntu 20.04 Installer
- [x] Remove prerelease version and create tag
- [ ] Email Blast

**Comment by jmarrec** [comment]
Windows 10: clean VM.

I got the usual Windows defender warning when installing.
The CLI is functional, used it to create the exampleModel

```
C:\openstudioapplication-1.2.0-rc3\bin\openstudio.exe -e "m = OpenStudio::Model::exampleModel(); m.save('example.osm')"
```

Loaded it

Clicked through all tabs. Changed things randomly.
GeometryPreview works.
Added BCL measure openstudio_results
Ran simulation successfully.
Was able to inspect the reports.

**Comment by jmarrec** [comment]
My testing of https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.2.0-rc6

* [x] Ubuntu 18.04 (dev machine)
* [x] Ubuntu 20.04 (dev machine)
* [X] Windows 10 (20H2, clean VM)
* [ ] macOS

**Comment by arif-hanif** [comment]
Mac (Big Sur 11.4)

I got the usual security warning that not from a verified source.

- [x] openstudio app 
- [x] geometry preview
- [x] checked different tabs
- [ ] ran simulation
- [ ] added measure

**Comment by arif-hanif** [comment]
Windows 10

I got the usual security warning that not from a verified source, during the install.

- [x] openstudio app 
- [x] geometry preview
- [x] checked different tabs
- [ ] added measure 
- [ ] ran simulation
