### ISSUE TITLE
OSApp 1.3.0: Release checklist

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#456]
- [x] Update icons
- [x] Release Notes
- [x] Update OSM libraries to SDK 3.3.0
- [x] Test Windows Installer
- [ ] Test Mac M1 Installer
- [ ] Test Mac x64 Installer
- [ ] Test Ubuntu 18.04 Installer
- [ ] Test Ubuntu 20.04 Installer
- [x] Remove prerelease version and create tag
- [x] Email Blast
