### ISSUE TITLE
OpenStudioApplication 1.4.0 - Release Checklist

### ISSUE THREAD

**Issue by macumber** [openstudiocoalition/OpenStudioApplication#507]
- [x] Update icons
- [x] Release Notes (include note about ARM for Mac and Windows)
- [x] Update OSM libraries to SDK 3.4.0
- [x] Test Windows Installer
- [x] Test Mac M1 Installer
- [x] Test Mac x64 Installer
- [x] Test Ubuntu 18.04 Installer
- [x] Test Ubuntu 20.04 Installer
- [x] Remove prerelease version and create tag
- [x] Email Blast
