### ISSUE TITLE
 OpenStudioApplication 1.6.0 - Release Checklist #507 

### ISSUE THREAD

**Issue by jmarrec** [openstudiocoalition/OpenStudioApplication#602]
- [ ] Release Notes
- [ ] Update OSM libraries to the right SDK version
- [ ] Test Windows x64 Installer
- [ ] Test Mac arm64 (M1) Installer
- [ ] Test Mac x64 Installer
- [ ] Test Ubuntu 20.04 x64 Installer
- [ ] Test Ubuntu 22.04 x64 Installer
- [ ] Test Ubuntu 22.04 arm64 Installer
- [ ] Remove prerelease version and create tag
- [ ] Email Blast
